production:
  adapter: <%= ENV['BRISA_WS_REDIS'] ? 'redis' : 'async' %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: brisa

development:
  adapter: <%= ENV['BRISA_WS_REDIS'] ? 'redis' : 'async' %>
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: brisa-dev

test:
  adapter: async
